name:                 decision-tree
version:              0.1.0.0
visibility:           public
id:                   decision-tree-0.1.0.0-inplace
key:                  decision-tree-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           lauri.lattila@gmail.com
author:               Lauri Lättilä
category:             Machine Learning
abi:                  inplace
exposed:              True
exposed-modules:
    DecisionTreeRegressor HousingExample RandomForestRegressor

import-dirs:
    /home/rootuser/HaskellProjects/random-forest/dist-newstyle/build/x86_64-linux/ghc-9.6.7/decision-tree-0.1.0.0/build

library-dirs:
    /home/rootuser/HaskellProjects/random-forest/dist-newstyle/build/x86_64-linux/ghc-9.6.7/decision-tree-0.1.0.0/build

library-dirs-static:
    /home/rootuser/HaskellProjects/random-forest/dist-newstyle/build/x86_64-linux/ghc-9.6.7/decision-tree-0.1.0.0/build

dynamic-library-dirs:
    /home/rootuser/HaskellProjects/random-forest/dist-newstyle/build/x86_64-linux/ghc-9.6.7/decision-tree-0.1.0.0/build

data-dir:             /home/rootuser/HaskellProjects/random-forest/.
hs-libraries:         HSdecision-tree-0.1.0.0-inplace
depends:
    base-4.18.3.0 bytestring-0.11.5.4
    cassava-0.5.4.1-02594e0b9a785864576ea77ce9627c91edf0328b0ce94eae8f32a495bc6b6d8b
    containers-0.7-0e46056358c0d6fbf3365197a4b04f92ed0e66b5c39aac0d51ee77f1baa52508
    directory-1.3.8.5
    parallel-3.3.0.0-ca6f0f890dfc9ea9c880ac771863c45f9cd0b03899e3db6e291975434dbaa47a
    random-1.3.1-a0b546c9357ed7f48cc7d509a46d4c9a14b6798796f7e850ba3aa653db265e47
    random-shuffle-0.0.4-40f43d63189dab069cfcf20e769bb3ef970bcda4d55c4d99d2de61fff3a2a6de
    vector-0.13.2.0-44a212992f25233ccd712d356a555b0bdaf449d50bb377a3a6ccef858aa7148f

haddock-interfaces:
    /home/rootuser/HaskellProjects/random-forest/dist-newstyle/build/x86_64-linux/ghc-9.6.7/decision-tree-0.1.0.0/doc/html/decision-tree/decision-tree.haddock

haddock-html:
    /home/rootuser/HaskellProjects/random-forest/dist-newstyle/build/x86_64-linux/ghc-9.6.7/decision-tree-0.1.0.0/doc/html/decision-tree
