name:                 random-forest
version:              0.1.0.0
visibility:           public
id:                   random-forest-0.1.0.0-inplace
key:                  random-forest-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           lauri.lattila@gmail.com
author:               Lauri Lättilä
category:             Machine Learning
abi:                  inplace
exposed:              True
exposed-modules:
    DecisionTreeRegressor HousingExample RandomForestRegressor
    VectorDecisionTreeRegressor VectorRandomForestRegressor

import-dirs:
    /home/rootuser/HaskellProjects/random-forest/dist-newstyle/build/x86_64-linux/ghc-9.6.7/random-forest-0.1.0.0/build

library-dirs:
    /home/rootuser/HaskellProjects/random-forest/dist-newstyle/build/x86_64-linux/ghc-9.6.7/random-forest-0.1.0.0/build

library-dirs-static:
    /home/rootuser/HaskellProjects/random-forest/dist-newstyle/build/x86_64-linux/ghc-9.6.7/random-forest-0.1.0.0/build

dynamic-library-dirs:
    /home/rootuser/HaskellProjects/random-forest/dist-newstyle/build/x86_64-linux/ghc-9.6.7/random-forest-0.1.0.0/build

data-dir:             /home/rootuser/HaskellProjects/random-forest/.
hs-libraries:         HSrandom-forest-0.1.0.0-inplace
depends:
    base-4.18.3.0 bytestring-0.11.5.4
    cassava-0.5.4.1-749913503c6fa9f9f1324472daf3077cc9dc9235878a456e4cda57cfb5db15dc
    containers-0.7-c28b9c375c5738b6184d6ee4e12937e9e9133e10e825961d33e556f6f73634aa
    directory-1.3.8.5
    parallel-3.3.0.0-3fb75754ae7b579f1497acf9b39777b25b9920813f50661df99ff91344e7a30d
    random-1.3.1-350cff0e5190fcc720eb60d3ee881aab97d8272dab904f3be025028a164c2ba5
    random-shuffle-0.0.4-98b2888c68ee5b561eebd8b94bf7798c8894839b730d52dd93b0e6006ec17b05
    vector-0.13.2.0-182056fb5a4b5b5ce58ebe79f1c17ee441813e264c8a9678c95534aab499099e

haddock-interfaces:
    /home/rootuser/HaskellProjects/random-forest/dist-newstyle/build/x86_64-linux/ghc-9.6.7/random-forest-0.1.0.0/doc/html/random-forest/random-forest.haddock

haddock-html:
    /home/rootuser/HaskellProjects/random-forest/dist-newstyle/build/x86_64-linux/ghc-9.6.7/random-forest-0.1.0.0/doc/html/random-forest
